### ISSUE TITLE
Content-Length header is wrong for non-ASCII bodies

### ISSUE THREAD

**Issue by akheron** [cprussin/purescript-httpure#101]
When computing the value for the Content-Length header, `String.length` is used. This is not correct for non-ASCII strings, as each character gets encoded to two or more bytes in UTF-8. For example, when using the string `"äö"` as the response body, there's `Content-Length: 2` but the content is actually 4 bytes long.

**Comment by cprussin** [comment]
:+1: very good catch.  I'm not sure what the best way is to solve this... I guess I could do `Buffer.fromString >>= Buffer.size`

**Comment by akheron** [comment]
The `byteLength` function doesn't seem to be very hard to implement in PS either, so I'd go there right away.

**Comment by cprussin** [comment]
I'm not so concerned about whether it's hard as I am concerned that it's nontrivial and isn't logic that really belongs in an http library--and I don't even have any proof that it's truly faster than the trivial approach. If it is faster, would it be better to put it in something like `Data.String`?

**Comment by akheron** [comment]
You're right. Let's do it the easy way first.
