### ISSUE TITLE
Add `sendFile` helper

### ISSUE THREAD

**Issue by cprussin** [cprussin/purescript-httpure#102]
Should take a path, automatically read and buffer the file, and automatically set the `Content-Type` response header.

**Comment by akheron** [comment]
... and eventually using the `sendfile` system call would of course be the most performant option. Not sure if it's possible in NodeJS.

**Comment by cprussin** [comment]
Great, as for using `sendfile` we can dig into what express does here and do the same thing, I feel confident enough that express is heavily optimized around here since it's been doing this on a massive scale for a long time, and we can port anything over that we need to.

So, a few things here:

1) I feel like `Data.MediaType` should enumerate all the possible media types with data constructors, something like:

```purescript
data MediaType = Json | Javascript | OctetStream | ...
```

Right now, it just creates a newtype wrapper around `String` and has helper functions for all the different types.  That feels like an odd pattern.

If we feel strongly enough about this, we may want to either have our own media type handling in HTTPure, or build a separate alternative to `Data.MediaType`.  But I don't know that we should or do feel strongly about this, just something I'd like to bring up for discussion.  @garyb in case you happen to see this, I'd love it if you don't mind weighing in on why `Data.MediaType` is the way it is and if using data constructors instead of just a newtype string wrapper may be problematic (and I'm happy to submit a PR to convert it if you think it should be data constructors instead).

2) I definitely think media type detection should not be part of HTTPure, there's a lot of border cases, especially with things like [magic](https://linux.die.net/man/5/magic) so it's easy to get wrong, and a lot of other folks have libs that do it right.  There might be something built in to node, I'm not sure.  I'll do research here and make sure what we use isn't custom home-rolled.

3) I definitely agree with streaming responses.  I'd say that's a prerequisite before building this helper.  Sorry I still haven't gotten on that--I had my first kid a few weeks back so my time for open source has been less than ideal.  It will happen soonish, I promise :)

**Comment by garyb** [comment]
Hey! Yeah, I can totally understand the desire for that. I originally wanted to do something cleverer for media types - and there's still definitely room for improvement, but an exhaustive enumeration is pretty much out of the question. There is something in the region of 2000 media types registered with IANA: https://www.iana.org/assignments/media-types/media-types.xhtml, and applications can often have custom media types too.

We could at least split the parts out rather than just having a plain newtype over a string, and have an exhaustive sum for the predetermined top-level names like "text", "image", "audio", and so on as laid out in https://tools.ietf.org/html/rfc6838, but there would probably still be a need for a constructor for custom cases there even.

**Comment by akheron** [comment]
> Sorry I still haven't gotten on that--I had my first kid a few weeks back so my time for open source has been less than ideal. It will happen soonish, I promise :)

No problem, I'm also a father an know exactly what you're talking about :)

I actually played a bit with streaming responses yesterday and might be able to whip up something myself.

**Comment by cprussin** [comment]
@garyb what about a programatically generated module that uses the table in the reference you sent?  Obviously I don't think anything in any PS module should maintain the media type enumeration manually, but if IANA already does so it shouldn't be so hard to use it to generate a purescript module to turn them into data constructors no?  For custom media types, we can just have a data constructor that takes a string, e.g.:

```purescript
data MediaType =
    1DInterleavedParityfec |
    3GpdashGoeReportXml |
    ... -- Generated code here
    Custom String

instance showMediaType :: Show MediaType where
    show 1DInterleavedParityfec = "application/1d-interleaved-parityfec"
    show 3GpdashGoeReportXml = "application/3gpdash-qoe-report+xml"
    ... -- Moar generated code
    show (Custom template) = template
```

Do the registries actually mean anything, other than providing some sense of organization for the types?

**Comment by cprussin** [comment]
Yeah, I think you're right that the mime type enumeration probably wouldn't be useful in this context.  I do think it could be useful in other contexts, for instance, providing a cleaner API for setting a `Content-Type` header... but probably not in this context.

I don't think the extension mapping is quite enough.  What about magic file data?

**Comment by cprussin** [comment]
Idea: using the patterns added in https://github.com/cprussin/purescript-httpure/pull/104, we could create a newtype around `String` called e.g. `File`, and create typeclass instances for `Streamable` and `Body`.  Then there would be no need for a specific helper for sending files and it could just be done something like:

```purescript
router _ = HTTPure.ok $ File "./my-super-duper-file.mspaint"
```

(Note we can't use `FilePath` from https://github.com/purescript-node/purescript-node-path because `FilePath` is just a type synonym for `String` and there's already typeclass instances for `String`)

**Comment by akheron** [comment]
> router _ = HTTPure.ok $ File "./my-super-duper-file.mspaint"

What to do if the file doesn't exist?

**Comment by cprussin** [comment]
Hmm good point, ok so back to a helper it is...

**Comment by cprussin** [comment]
@akheron could use a sounding wall for something that came up while I was working on this.

So, essentially, I was thinking about how to do error handling.  Problem is, with a stream, you don't know that the error has occurred until the `error` event has been dispatched.  This event won't be dispatched until running the body function, that is, `Body.write` in the `Body` typeclass.

So we need some way of handling errors from within the `Body` typeclass.  So the problem is, what's the right API for that.

Note that error-handling applies to _all_ streams, not just the file helper.  So what I'm leaning towards is something along the lines of this: instead of a `Body` typeclass for streams, we have a `Body` typeclass for something like `Tuple Stream (Error -> ResponseM)`.  Thoughts?  Any other ideas here?

**Comment by cprussin** [comment]
Having given some thought to this, I think this is best done as a contrib module and not part of the httpure core.  I'm going to close this ticket and will plan to publish a contrib module when I get time that will include the helper.
