### ISSUE TITLE
Empty query param value

### ISSUE THREAD

**Issue by akheron** [cprussin/purescript-httpure#127]
I find it quite confusing (although it's documented) that when the query string contains an empty value for some param, the value for that param is `"true"`:

```purescript
-- ?foo=
query !! "foo" == Just "true"
query !! "bar" == Nothing
```

I would find it more logical to return an empty string in this case:

```purescript
-- ?foo=
query !! "foo" == Just ""
query !! "bar" == Nothing
```

**Comment by cprussin** [comment]
Yeah, I agree with this, it is confusing.  It should be fixed.

For historical context: this came from the days before I understood fundeps and so the `Lookup` typeclass wasn't so robust, so doing something like `query !! "foo" == Nothing` would not be resolvable by the compiler without added type hints.  This is actually why `Lookup.at` exists.  Now that the fundep is there, we can probably clean up the `Lookup` typeclass a bit, and address this odd API as well.
