### ISSUE TITLE
Expose original request URL

### ISSUE THREAD

**Issue by cprussin** [cprussin/purescript-httpure#130]
We currently expose `fullPath` as a logging method, but this is constructed from the HTTPure request parts object and while it should be equivalent to the original request URL from a routing perspective, it isn't identical.  We should expose a way of getting the full original request URL from the request.

**Comment by paluh** [comment]
I've just dropped `fullPath` and added original URL to the `Request.Request`. If you agree with this changes I can create a PR:

https://github.com/cprussin/purescript-httpure/compare/master...paluh:fullPath

**Comment by paluh** [comment]
P.S.
Oh, sorry I've commit there also `shell.nix` changes so if you agree with this direction I'm going to cleanup this branch before PR ;-)

**Comment by cprussin** [comment]
So, I like the idea of adding access to `HTTP.requestURL`, but I'm not sure I like dropping `fullPath` entirely... it isn't completely equivalent to `HTTP.requestURL` and I would find the original `fullPath` also valuable for logging since it indicates what HTTPure matched (although maybe that can be solved batter by instead just having a log formatter that logs the components of the `Request` in a clearer format).

Regarding the `shell.nix` changes, I'd prefer to revert those, for the following reasons:

1. I'd prefer to keep `bower`, `jshint`, etc managed by `package.json` for now--that way is more accessible to folks who aren't on nix.
2. It's important to me to keep the package versions, as well as the `nixjs` and `nixpkgs` paths, as arguments to the nix module--I use those to test different package versions and packaging tools (e.g. `nix-shell --arg nixjs path/to/local/nixjs --arg purescript 1.12.5`).
3. Since HTTPure has simple package dependencies (and probably should remain that way easily work with a regular package set), there's no reason to introduce `spago`--`psc-package` serves our needs just fine (anyways it looks like you're configuring `nixjs` to export an overlay that has `spago` but you're not actually using the exported `spago` package).

**Comment by paluh** [comment]
What do you think about just adding `url` into the `Request` (`requestURL` name sounds a bit redundant in this context :-)) type:

https://github.com/cprussin/purescript-httpure/compare/master...paluh:add-request-url

**Comment by cprussin** [comment]
LGTM... open up a PR and I'll merge!

**Comment by paluh** [comment]
Cool! Done: https://github.com/cprussin/purescript-httpure/pull/155 ;-)
