### ISSUE TITLE
Console is missing as a dependency

### ISSUE THREAD

**Issue by justinwoo** [cprussin/purescript-httpure#132]
https://github.com/cprussin/purescript-httpure/blob/fe2e3f5f6de170002e23df6979561b1a59ab6660/src/HTTPure/Server.purs#L14

This breaks package set validation. Please add this to your bower.json and publish a patch version.

**Comment by cprussin** [comment]
Ah will do. Don't know how I missed that, I thought the package set validation succeeded. Is there something I missed?

**Comment by cprussin** [comment]
Fixed in v0.8.1

**Comment by justinwoo** [comment]
Thanks. I was pulling the latest version and that failed. This can be normally validated on bower with bower i -p (production) first, followed by then using normal bower i to install test dependencies

**Comment by cprussin** [comment]
Aha, so something got installed into devDependencies instead of dependencies. That helps. I thought this was a psc-package.json issue. Thanks for that added context!
