### ISSUE TITLE
Expose request path and query to enable custom route parsing?

### ISSUE THREAD

**Issue by JordanMartinez** [cprussin/purescript-httpure#144]
I really like the UX of [purescript-routing-duplex](https://github.com/natefaubion/purescript-routing-duplex). I was wondering whether this project would be interested in exposing the full path (including queries) in the request and move the current Lookup approach to its own module as a default route parser, so that the end-user could use their own route parser to properly handle things (like `purescript-routing-duplex`).

**Comment by cprussin** [comment]
I'm not opposed to a PR to add the full path, but I don't see any reason this would supersede or motivate removing the `Lookup` typeclass (which is useful for both routing and computing responses).

@paluh has started implementing this (see https://github.com/cprussin/purescript-httpure/issues/130) but never put in a PR; if you wanted to wrap that up and put in a PR for it I'd be more than happy to merge & release.

**Comment by JordanMartinez** [comment]
Oh, I don't mean remove lookup. I agree that that should stay. I meant move
it to its own module (which might already be the case).

>

**Comment by cprussin** [comment]
Yeah, lookup is implemented as a pretty simple typeclass (see https://github.com/cprussin/purescript-httpure/blob/master/src/HTTPure/Lookup.purs)

**Comment by cprussin** [comment]
FWIW httpure doesn't really have a "router"--httpure just parses the incoming request and takes a function that uses that parsed object to come up with a response.  It's just that out of the box, basic purescript pattern matching on the parsed data structure is pretty sufficient for most simple routing.  Even if you used an external router, you'd probably want the parsed request to be able to respond properly.

If you don't want the parsed request at all, you're probably not getting much if anything out of HTTPure.  You could probably use some of the internal classes directly (e.g. maybe https://github.com/cprussin/purescript-httpure/blob/master/src/HTTPure/Response.purs) but parsing the request is a large part of what HTTPure does.

**Comment by JordanMartinez** [comment]
Ok, thanks for clarifying that. For context, I've also been looking at `purescript-trout`, `hyper`, and `purescript-hypertrout` as I look at options for a PS server.

**Comment by cprussin** [comment]
You might be better off with something like hyper/trout if you want more batteries out of the box.

HTTPure is intended to be a pretty bare bones mapping of the HTTP spec into PureScript.  There is a type for each part of an HTTP request & response; an incoming request is parsed into the relevant types and run through your router function, which returns an HTTPure response.  HTTPure then writes the response out.  There isn't really anything else going on besides that.

Hyper contains many of the bells and whistles that would exist as third-party [Middleware](https://github.com/cprussin/purescript-httpure/blob/master/docs/Middleware.md) or just helper functions in HTTPure (things like HTTP auth, content negotiation form handling, etc).  But I'm not sure many of those bells and whistles exist in the wild yet (nothing is preventing them from being written, I just don't know that anyone has had the use case to write them).  I don't think it would ever make sense for those things to be part of HTTPure proper, but maybe in Contrib modules somewhere.

In any case, I would suggest HTTPure if you want something lightweight and closer to the metal (or are willing to contribute some Contrib work), and I would suggest Hyper if you're looking for more of those bells & whistles.

**Comment by JordanMartinez** [comment]
Ok. I'll look at hyper then. Should I close this issue?
