### ISSUE TITLE
Should functions on `Response` return `MonadAff m => m Response`

### ISSUE THREAD

**Issue by drewolson** [cprussin/purescript-httpure#146]
I'm curious if functions within `HTTPure.Response` should return `MonadAff m => m Response` rather than `ResponseM` (which is an `Aff Response`).

For example, `ok` would change from:

```purescript
ok :: forall b. Body.Body b => b -> ResponseM
```
to:

```purescript
ok :: forall m b. MonadAff m => Body.Body b => b -> m Response
```

This would allow users working within a monad stack to use `HTTPure.ok` directly rather than `liftAff $ HTTPure.ok`.

Thoughts?

**Comment by cprussin** [comment]
Yeah, I think that makes sense.  I think this could be done in a non-breaking way so it doesn't introduce some of the concerns I had in #134 , but it does make it a bit easier to use transformer stacks.
