### ISSUE TITLE
default `serve` binds to `localhost` (resulting in "connection refused" errors)

### ISSUE THREAD

**Issue by henry-mueller** [cprussin/purescript-httpure#153]
Issue:

Using the `serve` function with \ as shown in most any example newer versions of node.js (v13.2 in my case) will bind to `localhost:[your port]`.  This will work fine for all straight local development, but will not work as soon as you deploy in any way (for example, as soon as you put your app in a Docker container).  You will get "connection refused" error when you make a request.

I am fairly certain 
a) this was a change on the part of node.js API (the v6 docs say it will bind to 0.0.0.0 by default, the newer docs do not)
b) That I don't have to handle this on Express or Express clones... but I have not gone back and reviewed the code, I am just presuming I would remember having to go through this with other HTTP servers.

I only mention b) to make a very weak argument that HTTPure should be changed to not bind to localhost buy default or the API for `serve` be changed to make it more obvious.  But updating the docs would be a minimum very helpful things to do (and yes, I can PR that if you like).  

Work Around:

Use the `serve'` function and supply the hostname option:
`HTTPure.serve' {port: port, hostname: "0.0.0.0", backlog: Nothing} someRouter`

**Comment by cprussin** [comment]
If I'm understanding correctly the fix would be just changing line https://github.com/cprussin/purescript-httpure/blob/master/src/HTTPure/Server.purs#L84 to point to '0.0.0.0' instead of 'localhost', is that accurate?

I'm all for that change, the intention of the `serve` function was to "do the right thing" for most use cases, which I think is to bind to 0.0.0.0.

**Comment by henry-mueller** [comment]
> If I'm understanding correctly the fix would be just changing line https://github.com/cprussin/purescript-httpure/blob/master/src/HTTPure/Server.purs#L84 to point to '0.0.0.0' instead of 'localhost', is that accurate?
> 
> I'm all for that change, the intention of the `serve` function was to "do the right thing" for most use cases, which I think is to bind to 0.0.0.0.

In my opinion, yes.  I don't think there is any common production case for binding to `localhost`.  I only doubt myself because apparently no one else has run into this yet?  But as long as it is documented, any choice is defensible.  

Thanks for following up!  I'll commit to doing a PR for whichever choice you take.

**Comment by cprussin** [comment]
@henry-mueller Fixed in https://github.com/cprussin/purescript-httpure/pull/154.

Is this something you need a release for or can you wait until whenever the next release goes out?

**Comment by henry-mueller** [comment]
No rush, using the `serve'` is no problem at all.

**Comment by joneshf** [comment]
> I only doubt myself because apparently no one else has run into this yet?

It's way after the fact, but we ran into this when setting up `purescript-httpure` at work a couple years back. @cprussin helped out on Slack (explaining that we should use `0.0.0.0` instead of `localhost`). So, there's other people that have run into this problem, but I imagine that conversation is lost to the Slack paywall by now.

**Comment by paluh** [comment]
> I don't think there is any common production case for binding to localhost. 

@henry-mueller actually there are cases (like any reverse proxy setup etc.) and I strongly prefer "safe" default which would be "localhost / 127.0.0.1" and not "expose me everywhere - 0.0.0.0" setup. This hides node app from any public host interfaces.
