### ISSUE TITLE
Pursuit is not up to date with 0.10.0

### ISSUE THREAD

**Issue by cscalfani** [cprussin/purescript-httpure#164]
The change to `notFound` from `0.9.0`, the latest documented version, to `0.10.0` really threw me for a loop. It's a good change.

Having the docs up to date would've saved me and I suspect others similar confusion.

Thank you.

**Comment by cprussin** [comment]
Ah somehow I missed this, iirc there was some issue that prevented publishing to pursuit for some time so some versions don't have docs posted, but that was fixed some time ago and so at least the last few releases are there. Sorry for the confusion!

**Comment by cscalfani** [comment]
Thanks for doing this. This will help readers of my book.
