### ISSUE TITLE
Utils.replacePlus Only Replaces the First Occurrence

### ISSUE THREAD

**Issue by tmciver** [cprussin/purescript-httpure#165]
The function `HTTPure.Utils.replacePlus` only replaces the first occurrence of '+':

    > replacePlus "HTTPPure+is+A+purescript+HTTP+server+framework"
    > "HTTPPure%20is+A+purescript+HTTP+server+framework"

**Comment by cprussin** [comment]
Thanks for reporting and fixing @tmciver !
