### ISSUE TITLE
Is HTTPure production ready?

### ISSUE THREAD

**Issue by kee-oth** [cprussin/purescript-httpure#192]
Hi!

I know HTTPure hasn't reached V1 yet but I was curious about the maintainers' view on using it in production applications. I have a startup that will be building out a web API and I'm interested in using a PureScript framework for the task. HTTPure _seems_ to be one of the more active projects in this space but I'd still like to double check the status of this project and how dedicated the current maintainers are to developing and supporting HTTPure.

Thanks!

**Comment by afcondon** [comment]
It's a very nice project - have you looked for a maintainer to hand it off to on PureScript Discourse/Discord?

Many thanks for writing it in the first place!

**Comment by cprussin** [comment]
no I've not but that's a great idea, I'll post over there

**Comment by cprussin** [comment]
here you go: https://discourse.purescript.org/t/looking-for-maintainers-for-httpure/2961

**Comment by kee-oth** [comment]
@cprussin Thanks for letting the community know about your time constraints and inability to work on HTTPure! I wish I could take over this project but I'm very new to PureScript at the moment. Maybe if no one claims it in the next year or so... 😅

**Comment by j-nava** [comment]
I use HTTPure very often and would not like to see it getting stale. 
I can give it a shot maintaining it if no one else shows interest. At the very least I can find the time to keep it up-to-date, review PRs, and discuss the most important issues.

**Comment by sigma-andex** [comment]
@j-nava I could give you a hand on keeping it up to date (especially for the 0.15 release) since I'm also using httpure quite extensively. Though I'd prefer not to be the main maintainer since I don't really have the time in pushing it forward.

**Comment by j-nava** [comment]
@sigma-andex that's great to hear!
Yes, I'd rather have more of a supporting role if someone else would step up as a main maintainer, but I'm willing to try before seeing this nice project getting archived or having development completely halted.

**Comment by cprussin** [comment]
Yeah, sounds good to me.  Whatever I can do to keep the project alive by the folks who care about it and get to use it, I'm happy to do.

**Comment by sigma-andex** [comment]
We can also have a call in the discord one of these days if you want

**Comment by cprussin** [comment]
I'm pleased to announce that [CitizenNet](https://www.citizennet.com/) has agreed to take ownership over httpure and drive continued maintenance.

I'm really excited about this change -- it will be great to get this project in the hands of a group of folks who use it professionally and in production.  I'm confident they'll be able to drive improvements in a way I'd never be able to keep up with.

Thanks especially to @davezuch and @joneshf from CitizenNet for their willingness to step up here and for their past contributions!

@sigma-andex and @j-nava, I really appreciate you both volunteering to pitch in as well, and I'm sure CitizenNet will value your input and assistance moving forward if the offer still stands.

I'll make the change in github now to transfer the repo over to the CitizenNet org.  Thanks again all!

**Comment by JordanMartinez** [comment]
Just FYI. I believe this transfer will need an update in the registry repo for this package's URL. The corresponding files in the package set repo should also be updated.
